### ISSUE TITLE
Issue #1: Responsive

### ISSUE THREAD

**Issue by Alexandroidd** [trevans24/mike-tysons-knock-out#2]
On opening your game in my browser noticed that your homepage "go" button was completely obscured by the floating bouncing text. Had to zoom out to 90% of browser window to see it. I would look into this immediately before nintendo has a freakin heart attack.  Also had trouble clicking it from 100% view, because it showed up eventually once my mouse hovered over it but then seemed to be having problems getting around the banner. Looking more into this. The "X" in the top right of the main screen is confusing, thought I was supposed to click it for some reason. ---- yeah after looking at home page again, only the middle of the GO button is clickable, just a heads up.

**Comment by trevans24** [comment]
might be the media query that was on the css...changed now
