### ISSUE TITLE
Issue #2: Scoring

### ISSUE THREAD

**Issue by Alexandroidd** [trevans24/mike-tysons-knock-out#4]
So I just racked up over 100 points off of one punch on Tyson's face. Seems like as long as I hold the punch button it continues to rack up points. I would definitely fix this as well, seems like it's probably not too hard either, so that only one punch = one point.  ---- Okay, looked at the code a little, found your scoring function and how you had it attached to the key down punch. I would put it on the retract part of the code and see if that doesn't isolate it, since you can't "let go" for an indefinite amount of time. Seems like no problemooooooo .Enjoy your weekend broham.

**Comment by trevans24** [comment]
fixed
